---
title: "Lab7 - Solutions"
subtitle: "Advanced Topics in Causal Inference"
author: "Pablo Freyria"
date: "11/23/2021"
output: pdf_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
setwd("~/Berkeley Classes/2021Fall/Causal2/Labs")
library(ltmle)

```

Data Structure 1
```{r Q1}
load("DataStructure1.RData")
head(ObsData1)

ObsData1$DeltaY[is.na(ObsData1$DeltaY)] <- 0

Anodes <- c("A","Delta")
Lnodes <- "L"
Ynodes <- "DeltaY"
abar <- list(c(1,1),c(0,1))

results1 <- ltmle(ObsData1,Anodes = Anodes,Lnodes = Lnodes,Ynodes=Ynodes,
                  Qform=c(L="Q.kplus1~W+A",DeltaY="Q.kplus1~L+A+W+A:W"),
                   gform = c(A = "A ~ W",Delta = "Delta ~ W + A + L"),
                  abar = abar, stratify = TRUE )

results1.gcomp <- ltmle(ObsData1,Anodes = Anodes,Lnodes = Lnodes,Ynodes=Ynodes,
                  Qform=c(L="Q.kplus1~W+A",DeltaY="Q.kplus1~L+A+W+A:W"),
                   gform = c(A = "A ~ W",Delta = "Delta ~ W + A + L"),
                  abar = abar, stratify = TRUE,gcomp = TRUE )

summary(results1,"tmle")
summary(results1,"iptw")
summary(results1.gcomp,"gcomp")
```

Data Structure 2
```{r Q2}
load("DataStructure2.RData")
head(ObsData2)

Anodes <- c("A1","A2","A3","A4")
Lnodes <- c("L1","L2","L3","L4")
Ynodes <- "Y"
abar <- list(c(1,1,1,1),c(0,0,0,0))

results2 <- ltmle(ObsData2,Anodes = Anodes,Lnodes = Lnodes,Ynodes=Ynodes,
                  abar = abar)

results2.gcomp <- ltmle(ObsData2,Anodes = Anodes,Lnodes = Lnodes,Ynodes=Ynodes,
                  abar = abar, gcomp = TRUE )

summary(results2,"tmle")
summary(results2,"iptw")
summary(results2.gcomp,"gcomp")

```

MSM

```{r MSM}

```
Data structure 4
```{r Q4,warning=FALSE,message=FALSE}
load("DataStructure4.RData")
head(ObsData4)

ObsData4$C1 <- BinaryToCensoring(is.censored = ObsData4$C1)
ObsData4$C2 <- BinaryToCensoring(is.censored = ObsData4$C2)
head(ObsData4)


Anodes <- c("A1","A2")
Lnodes <- c("L1","L2")
Cnodes <- c("C1","C2")
Ynodes <- c("Y2","Y3")
abar <- list(c(1,1),c(0,0))

results4 <- ltmle(ObsData4,Anodes = Anodes,Lnodes = Lnodes,
                  Cnodes=Cnodes,Ynodes=Ynodes,survivalOutcome = T,
                  abar = abar)

results4.gcomp <- ltmle(ObsData4,Anodes = Anodes,Lnodes = Lnodes,
                        Cnodes=Cnodes,Ynodes=Ynodes,survivalOutcome = T,
                  abar = abar, gcomp = TRUE )

summary(results4,"tmle")
summary(results4,"iptw")
summary(results4.gcomp,"gcomp")
```

Data Structure 0
```{r DS0}
load("DataStructure0_dtr.Rdata")
head(ObsData0_dtr)

Anodes <- c("A1","A2")
Lnodes <- c("L1","L2")
Ynodes <- "Y"
abar = cbind(ObsData0_dtr$L1 < 0, ObsData0_dtr$L2 < 0)

Qform <- c(L2="Q.kplus1~L1+A1",Y="Q.kplus1~L1:A1 + L2:A2")
results0_dtr <- ltmle(ObsData0_dtr,Anodes=Anodes,Lnodes=Lnodes,Ynodes=Ynodes,
                  abar=abar,Qform=Qform)
results0_dtr.gcomp <- ltmle(ObsData0_dtr,Anodes=Anodes,Lnodes=Lnodes,Ynodes=Ynodes,
                  abar=abar,Qform=Qform,gcomp = TRUE)

summary(results0_dtr,"tmle")

```